### ISSUE TITLE
generate in some x-goog headers for Rust clients

### ISSUE THREAD

**Issue by codyoss** [googleapis/google-cloud-rust#249]

**Comment by coryan** [comment]
Do we have a full list of what `x-goog-*` headers we want to generate before closing this?  I started with `x-goog-api-client`, but do we also need `x-goog-request-params`?  That seems redundant for HTTP+JSON.

**Comment by codyoss** [comment]
I think what you have done is fine. We will eventually do a full AIP audit and can evaluate request params at that time.
