### ISSUE TITLE
language codecs should register reserved words

### ISSUE THREAD

**Issue by codyoss** [googleapis/google-cloud-rust#36]
Each language has a bunch of case-sensitive "words" that are keywords/reserved in the language spec. We need to register these so we can do name sanitation and possibly identifier mangling do we don't generate invalid code.

**Comment by coryan** [comment]
I would like to help with this.

I think the name mangling is going to be language specific too, right?  Rust supports `r#{keyword}` to mangle keywords, but that won't work in other languages.

I think the codec will need to define a function to mangle keywords.  Or maybe things like:

https://github.com/googleapis/google-cloud-rust/blob/d86962b14d9218aac4a9e78946b22cbda187f397/generator/internal/genclient/templatedata.go#L287-L294

should just return the name after style and mangling via the codec, as in:

```go
func (f *field) Name() string {
	return f.c.FieldName(f.s, f.state)
```
