### ISSUE TITLE
[sidekick] Consider making templates embeddable 

### ISSUE THREAD

**Issue by dangazineu** [googleapis/google-cloud-rust#413]
If I build sidekick into a binary, I still need to provide it with a templates folder for it to function. While it may be useful to override the templates location for development, it probably makes more sense for the templates to be bundled with the binary so it is self-contained. See [embed](https://pkg.go.dev/embed) for reference.

**Comment by coryan** [comment]
You saved me the time to create this feature request.  I was working on it.
