### ISSUE TITLE
Build automation to ensure generator and generated code are always in sync

### ISSUE THREAD

**Issue by dangazineu** [googleapis/google-cloud-rust#560]
Ideally, each PR that changes the inputs to code generation (generator behavior, or the contents of the `sidekick.toml` files) would also include the update this change causes to the generated files. This is useful because the next developer making changes to the generator will be able to validate that their changes have no unintended side effects, by just re-running the generator.

I think this could be done as a GHA that runs the generator on top of the PR, and fails the check if a git diff is found.

**Comment by coryan** [comment]
> I think this could be done as a GHA that runs the generator on top of the PR, and fails the check if a git diff is found.

We are doing that for the Rust code in `src/generated`:

https://github.com/googleapis/google-cloud-rust/blob/49baaf15c0474ecd717165a1badfe9842a55ba96/.github/workflows/sdk.yaml#L122-L129

and for the golden files:

https://github.com/googleapis/google-cloud-rust/blob/49baaf15c0474ecd717165a1badfe9842a55ba96/.github/workflows/generator.yaml#L48-L50

Did you have something else in mind?

**Comment by dangazineu** [comment]
oh, I know what was my mistake... I didn't run `cargo fmt` after the refresh, and assumed the differences were stale changes.
